name: CMake on multiple platforms

on:
  push:
    branches: [ "dev" ]
    tags: [ "v1.2" ]
  pull_request:
    branches: [ "dev" ]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      
      matrix:
        build_type: [ Release ]
        
        include:
          # Windows configurations
          - os: windows-latest
            cpp_compiler: cl
          - os: windows-latest
            cpp_compiler: g++
          - os: windows-latest
            cpp_compiler: clang++
            
          # Linux configurations
          - os: ubuntu-latest
            cpp_compiler: g++
          - os: ubuntu-latest
            cpp_compiler: clang++
            
          # macOS configurations
          - os: macos-latest
            cpp_compiler: clang++
          - os: macos-latest
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4

      # Windows compiler setup
    - name: Setup MSVC (Windows)
      if: matrix.os == 'windows-latest' && matrix.cpp_compiler == 'cl'
      uses: ilammy/msvc-dev-cmd@v2

    - name: Install MSYS2 compilers (Windows)
      if: matrix.os == 'windows-latest' && (matrix.cpp_compiler == 'g++' || matrix.cpp_compiler == 'clang++')
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >
          gcc
          clang

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: choco install ninja -y

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install ninja

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libx11-dev

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -G Ninja
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }}
      
    - name: Determine Executable Name
      id: exe-name
      shell: bash
      run: |
        EXE_PATH="${{ steps.strings.outputs.build-output-dir }}/my_application"
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          EXE_PATH="${EXE_PATH}.exe"
        fi
        echo "exe_path=$EXE_PATH" >> $GITHUB_OUTPUT

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: executable-${{ matrix.os }}-${{ matrix.cpp_compiler }}
        path: ${{ steps.exe-name.outputs.exe_path }}
