name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        cpp_compiler: [g++, clang++, cl]
        include:
          # Windows configurations
          - os: windows-latest
            cpp_compiler: cl
          - os: windows-latest
            cpp_compiler: g++
          - os: windows-latest
            cpp_compiler: clang++
          # Linux configurations
          - os: ubuntu-latest
            cpp_compiler: g++
          - os: ubuntu-latest
            cpp_compiler: clang++
          # macOS configurations
          - os: macos-latest
            cpp_compiler: clang++
          - os: macos-latest
            cpp_compiler: g++
            
        exclude:
          - os: macos-latest
            cpp_compiler: cl
          - os: ubuntu-latest
            cpp_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install ninja

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libx11-dev
        
    # Setup MSVC environment for Windows when using 'cl'
    - name: Setup MSVC
      if: matrix.os == 'windows-latest' && matrix.cpp_compiler == 'cl'
      uses: microsoft/setup-msbuild@v2

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake (Windows and cl)
      if: matrix.os == 'windows-latest' && matrix.cpp_compiler == 'cl'
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64 && 
        cmake -B %GITHUB_WORKSPACE%/build
          -DCMAKE_CXX_COMPILER=cl
          -DCMAKE_BUILD_TYPE=Release
          -G "Ninja"
          -S %GITHUB_WORKSPACE%

    - name: Configure CMake
      if: matrix.cpp_compiler != 'cl'
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -G Ninja
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
